### PR TITLE
PostgreSQL support

### PR DESCRIPTION
**Pull request by ptitfred**
```nix
{ ... }:

{
  personal-infrastructure.postgresql = {
    enable = true;
    available-on-tissue = true;
    users = {
      user1 = {
        databases = [ "db_user1" "db_service1" ];
        initialPassword = "SCRAM-SHA-256$4096:DoZ1ed1syIYfoKWgDdHXbQ==$tf8f8l10T/nt7v4rRl0xM3UoXltOD+ddO+oSwMHmbVQ=:YmxZ7hPnJcrQ3g0F3KEwrYwQWOrN2MQvH4aFjmQrW3M=";
        superuser = true;
      };
      service1 = {
        databases = [ "db_service1" ];
        initialPassword = "SCRAM-SHA-256$4096:z+/dX1i1UxgegJd1PCeSYA==$mjdoWKH53eKVtC8KfnYg3tN0DThzEuHAOLAEQT1zZ+A=:6v6roQOItHDE0vHnkv7XDc2YKppebiwPoEk0wsFB/b0=";
      };
    };
  };
}
```

2 databases will be created (if missing):
- `db_user1`
- `db_service1`

2 users will be created (if missing):
- `user1` ; this one will have access to both databases
- `service1` ; this one only has access to its own database

`user1` can also create databases and roles as a super-user.

Both users are given a password, hashed in [SCRAM-SHA-256](https://www.postgresql.org/docs/current/auth-password.html). This PR also packages [this tool](https://github.com/supercaracal/scram-sha-256) to forge such hashes.

The server is made accessible locally and on the tissue interface (wireguard).

### CODE REVIEW

**Comment by Neustradamus** [comment]
Good job!

Linked to:
- https://github.com/scram-sasl/info/issues/1

**Comment by ptitfred** [comment]
Thank you @Neustradamus, I didn't expect anybody to have a look at this.

I don't see the link with SCRAM-SASL. Would you care explaining?

**Comment by Neustradamus** [comment]
@ptitfred: It is to promote more security in the World ^^

**Comment by ptitfred** [comment]
Thank you.

You realize I'm no contributor to PostgreSQL right?

**Comment by Neustradamus** [comment]
Yep

**Pull request merged**
